#pragma once

#ifdef TAPPING_TERM
#undef TAPPING_TERM
#endif
#define TAPPING_TERM 150
#define TAPPING_TOGGLE 1


#define PERMISSIVE_HOLD

// TODO: #define IGNORE_MOD_TAP_INTERRUPT
// TODO: #define IGNORE_MOD_TAP_INTERRUPT_PER_KEY



#define RGBLIGHT_DEFAULT_MODE RGB_MATRIX_TYPING_HEATMAP

#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYER_BLINK
